services:
  whisperlive:
    build:
      context: ./whisperLive_server
      dockerfile: Dockerfile.gpu
    ports:
      - "9090:9090"
    volumes:
      - ./whisperLive_server:/app
    environment:
      - PYTHONUNBUFFERED=1

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1

  ollama:
    image: ollama/ollama:latest
    volumes:
        - ./ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    ports:
        - "11434:11434"